### ISSUE TITLE
fix issues with writing/reading

### ISSUE THREAD

**Issue by joachimmetz** [libyal/libewf#38]
- [x] ~~fix https://github.com/libyal/libewf/issues/8 - added test coverage~~
- [x] ~~fix https://github.com/libyal/libewf/issues/22 - handling split images~~
  - ~~determine why chunks are seen as corrupt, also for EWF version 1~~
- [x] ~~update man pages https://github.com/libyal/libewf/issues/27~~
- [x] ~~fix https://github.com/libyal/libewf/issues/29~~
  - ~~fixed unmanaged "corrupted" chunk data~~
- [x] ~~fix last chunk write issue in split images~~
- [x] ~~determine why read falls back to table2~~
- [x] ~~improve handling missing chunks list~~
- [x] ~~restrict resources used by multi-threaded approach~~
- [x] ~~test and fix issues with new read/write chunk API~~
- [x] ~~look into report of ewfverify -l not logging anything?~~
- [x] ~~look into https://github.com/libyal/libewf/issues/35~~
- [x] ~~look into https://github.com/libyal/libewf/issues/93~~
- [x] ~~look into slow write chunk for version 2 format~~
- [x] complete chunk group size limitation

**Comment by joachimmetz** [comment]
```
        Command being timed: "ewfverify -j4 -x zero.acquire.E01"
        User time (seconds): 7655.70
        System time (seconds): 639.59
        Percent of CPU this job got: 189%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:13:04
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 624676
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 161453
        Voluntary context switches: 335875148
        Involuntary context switches: 26915
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by joachimmetz** [comment]
```
        Command being timed: "ewfacquire -B 2199023255552 -C Case -D Description -E Evidence -e Examiner -m removable -M logical -N Notes -j 4 -P 512 -t zero.acquire -u -cdeflate:empty-block -fencase7-v2 /dev/zero"
        User time (seconds): 4285.53
        System time (seconds): 927.34
        Percent of CPU this job got: 164%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 52:50.97
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 741820
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 394889
        Voluntary context switches: 355439092
        Involuntary context switches: 20744
        Swaps: 0
        File system inputs: 0
        File system outputs: 10487104
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by joachimmetz** [comment]
```
ewfverify -l test.log floppy-encase5.04a-nohash.E01 
ewfverify 20160410

Verify started at: Apr 12, 2016 20:52:43
This could take a while.

Verify completed at: Apr 12, 2016 20:52:43

Read: 1.4 MiB (1474560 bytes) in 0 second(s)

MD5 hash stored in file:		N/A
MD5 hash calculated over data:		ae1ce8f5ac079d3ee93f97fe3792bda3

ewfverify: SUCCESS
```
```
cat test.log 
MD5 hash stored in file:		N/A
MD5 hash calculated over data:		ae1ce8f5ac079d3ee93f97fe3792bda3
```
